chat_app/urls.py
from django.urls import path, include
from . import views
app_name = "chat_app"

urlpatterns = [
    path("", views.home),
    path("user_input/", views.user_check, name="user_input"),
    path("send", views.send, name="send_message")
]

chat_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("chat_app.urls"))
]

chat_app/models.py
from django.db import models
from django.db.models import Q


class Room(models.Model):
    sender = models.CharField(max_length=30)
    receiver = models.CharField(max_length=30)
    group = models.CharField(max_length=80,blank=True)

    def save(self, *args, **kwargs):

        # method for categorising any two model classes having same pair of users but opposite Roles

        if Room.objects.filter(Q(sender=self.receiver) & Q(receiver=self.sender)).exists():
            obj = Room.objects.filter(Q(sender=self.receiver) & Q(receiver=self.sender))
            self.group=obj[0].group

        else:
            self.group = f"{self.sender}_{self.receiver}"

        super(Room, self).save()


class Message(models.Model):

    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(max_length=1000)
    time = models.DateTimeField(auto_now=True)

chat_app/views.py
import string
from django.shortcuts import render, HttpResponse
from .models import Message, Room
from django.db.models import Q
from . import Encryption


def home(request):
    return render(request, "home.html")


def user_check(request):

    # Method to render our message intake HTML page and listing all the previous chat.

    Sender = request.POST['Sender']
    Receiver = request.POST['Receiver']
    secret_key = request.POST['secret_key']
    R_message = []

    if Room.objects.filter(Q(sender=Sender) & Q(receiver=Receiver)).exists():

        room_id = Room.objects.filter(Q(sender=Sender)&Q(receiver=Receiver))[0].id
        group = Room.objects.get(id=room_id).group
        r_room = Room.objects.filter(group=group)

        if len(r_room) > 1:

            r_message = Message.objects.filter(Q(room=r_room[0])|Q(room=r_room[1]))

        else:

            r_message = Message.objects.filter(room=r_room[0])

    else:
        new_room = Room.objects.create(sender=Sender,receiver=Receiver)
        new_room.save()
        room_id = new_room.id
        group = new_room.group
        r_room = Room.objects.filter(group=group)

        if len(r_room) > 1:

            r_message = Message.objects.filter(Q(room=r_room[0]) | Q(room=r_room[1]))

        else:

            r_message = Message.objects.filter(room=r_room[0])

    for i in r_message:
        R_message.append(Encryption.decrypt(i.body, secret_key, string.printable))

    return render(request, "messages.html", {"Id": room_id, "Required_message": R_message})


def send(request):

    # Method to save entries in our database

    body = request.POST['body']
    encrypted_body = Encryption.encrypt(body, string.printable)
    room_id = request.POST['Id']

    new_message = Message.objects.create(room=Room.objects.get(id=room_id), body=encrypted_body)
    new_message.save()
    return HttpResponse("Message sent")

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'chat_app:user_input'%}">
    {%csrf_token%}
    Your username: <input type="text" name="Sender"><br>
    Receiver username: <input type="text" name="Receiver"><br>
    Enter your secret key: <input type="text" name="secret_key">
    <input type="submit" value="submit">

</form>

</body>
</html>

templates/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script crossorigin="anonymous"
            integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <style>
        .container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}




    </style>
</head>
<body>


<div id="display">

    <div class="container">

        {%for i in Required_message%}
            <h4>{{i}}</h4>
        {%endfor%}

    </div>
</div>

<form action="{% url 'chat_app:send_message'%}" id="post-form" method="post">
    {%csrf_token%}
    <input id="body" name="body" type="text">
    <input id="room_id" name="Id" type="hidden" value="{{Id}}">
    <input type="submit" value="send">
</form>



<!--<code block>-->
<script type="text/javascript">
  $(document).on('submit','#post-form',function(e){
    e.preventDefault();

    $.ajax({
      type:'POST',
      url:'/send',
      data:{
          body:$('#body').val(),
          Id:$('#room_id').val(),
        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
      },
      success: function(data){
         console.log(data)
      }
    });
    document.getElementById('body').value = ''
  });
</script>
<!--<end of code block>-->

<!--this code block is inspired from - https://github.com/tomitokko/django-chat-app/blob/main/templates/room.html-->
<!--To prevent our page from reloading or going to another page.-->


</body>
</html>